-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR FROM ICECREAM_INFO,FIRST_HALF
    WHERE TOTAL_ORDER > 3000
    AND INGREDIENT_TYPE = "fruit_based"
    AND ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
    ORDER BY TOTAL_ORDER DESC
    ;